### ISSUE TITLE
Teacher Review: Week 4

### ISSUE THREAD

**Issue by ncrxue** [D1935827V/spring_portfolio#20]

**Comment by jm1021** [comment]
Mini lab hack 4 and 6 by N.  Not talking much about others.   .50

**Comment by avabrooks** [comment]
General Comments: README is super confusing. Also doesn't help that it was simultaneously updating while we were grading, 2 days after the work was due. Confused about why there were so many links to different places with the same information(journal, ticket information on journal, and weird half-finished documents). The Scrum board is somewhat disorganized. Not all tickets have tangibles, descriptions, and screenshots are not the best medium. Try using checklists with links to code to better organize your tickets and scrum board.

**Comment by risaiwazaki** [comment]
Brayden: Nice work on having the tangibles and checklists on your ticket! However, the deadline you set for yourself is a little confusing. Your test corrections and notes link was confusing & not sure why the ticket was in the document. Test correction descriptions are missing. Try making a big journal where you can update it every week instead of making a new journal for each week :). A little confused on coding commits as most of them are READme. 

In your case, thank you for having one of the more organized tickets in your group! Next time you can also include your name to the tickets to make things easier for you & the grader.

**Comment by risaiwazaki** [comment]
Calvin: Good tickets, thanks for providing tangibles. You have very detailed notes and test corrections, it is very much appreciated. Thanks for having links available and easy to find and good organization. Next time, try to combine tickets of the same topic!

**Comment by risaiwazaki** [comment]
Nic: Your ticket has no tangibles or descriptions. It is very confusing. We saw you added commits to code but it is hard to access when there is no link to tangibles or code. Test corrections are incomplete. Include screenshots of the score. You linked unit three to the READme instead of unit 4, but unit 3 was still incomplete.

**Comment by risaiwazaki** [comment]
Dane: There are no links or any evidence of work being done on the READme. It is very confusing to navigate it. There have been no commits in the last 2 weeks. There is stuff on the READme but confused as most of it does not have much explanation. Not sure when that work was done based on commit history. No test corrections or notes provided (if you got 100%, please provide a screenshot). I'm sure you are doing work, just unclear where it is happening or if you are the one committing. Next time please specify where the work is happening.
